name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install steamcmd
        run: |
          sudo add-apt-repository multiverse
          sudo dpkg --add-architecture i386
          sudo apt update
          echo steam steam/question select "I AGREE" | sudo debconf-set-selections
          echo steam steam/license note '' | sudo debconf-set-selections
          sudo apt install steamcmd -y
      - name: Setup steamcmd
        run: |
          steamcmd +login anonymous +quit
      - name: Create user config
        run: |
          echo "${{ secrets.USER_CONFIG }}" | base64 --decode > ~/Steam/config/config.vdf
      - name: Test steamcmd?
        run: |
          steamcmd +login NS2BDT +quit
